/** Full editorial story bodies for test seeding — 400–600 words each */

export type TestStoryDef = {
  slug: string
  title: string
  category: string
  authorSlug: string
  location: string
  featured: boolean
  monthsAgo: number
  imageIndex: number
  excerpt: string
  paragraphs: string[]
}

export const TEST_STORIES: TestStoryDef[] = [
  {
    slug: 'lake-that-fed-a-nation-disappearing',
    title: 'The Lake That Fed a Nation Is Disappearing — and Nobody in Power Seems to Notice',
    category: 'Water',
    authorSlug: 'amara-diallo',
    location: 'Lake Chad Basin',
    featured: true,
    monthsAgo: 0,
    imageIndex: 0,
    excerpt:
      'Lake Chad has shrunk by 90% since the 1960s. For fishermen in Bol and farmers in Baga, the collapse is not a future scenario — it is this season\'s empty net and next month\'s migration decision.',
    paragraphs: [
      'In 1963, Lake Chad covered roughly 25,000 square kilometres — a vast inland sea that fed tens of millions of people across four countries. Today it is closer to 1,500 square kilometres. The numbers are so extreme they sound like a typo. They are not.',
      'On the shores near Bol, in Chad, fisherman Hassan Mahamat pulls in nets that once held dozens of species. Now he catches mostly sand and plastic. "My father fished this lake for forty years," he says, mending a net he knows will come up light again tomorrow. "I am teaching my son to drive a motorcycle taxi instead."',
      'The causes are a braid of climate and governance failures. Rainfall in the Sahel has become more erratic, while upstream withdrawals for irrigation have accelerated. National governments dispute who bears responsibility; regional commissions produce plans that arrive years after the water has gone.',
      '**Communities improvising where states fail**\nIn the village of Ngouboua, women\'s cooperatives have dug deeper wells and planted drought-tolerant millet varieties, sharing seed banks when the rains fail twice in a row. These are survival strategies, not solutions — but they are what keeps families fed when ministries miss their meetings.',
      'Scientists at the Lake Chad Basin Commission estimate that without intervention, the lake could lose another third of its surface area by 2040. Yet adaptation funding pledged at successive climate summits has reached few of the fishing villages that line the receding shore.',
      '> "We hear about billions for climate on the radio. We see sacks of grain when the election is near. The lake does not vote." — Cooperative leader, Baga',
      'There is one modest sign of hope: a canal project linking the lake to the Ubangi River, debated for decades, has finally received partial funding. Engineers say it could stabilise water levels within a generation. Hassan Mahamat is sceptical. "I will believe it," he says, "when I see water where my boat used to float."',
      'Until then, the disappearance of Lake Chad remains Africa\'s most visible warning — a body of water vanishing while the world discusses it in the conditional tense.',
    ],
  },
  {
    slug: 'ugandan-farmer-food-forest',
    title: 'How One Ugandan Farmer Turned a Dying Hillside Into a Food Forest',
    category: 'Agriculture',
    authorSlug: 'james-mwangi',
    location: 'Kabale, Uganda',
    featured: false,
    monthsAgo: 1,
    imageIndex: 5,
    excerpt:
      'On a steep plot in Uganda\'s highlands, Grace Tumusiime replaced maize monoculture with terraces, nitrogen-fixing trees, and indigenous beans — and tripled her family\'s harvest within four seasons.',
    paragraphs: [
      'The hillside above Grace Tumusiime\'s home in Kabale used to slide with every heavy rain. Soil ran into the valley like rust. Her maize yields fell year after year as the rains came later and left sooner.',
      'An extension officer from a local NGO introduced her to agroforestry — not as a lecture, but as a bet: plant calliandra and leucaena between terrace rows, intercrop climbing beans with banana, and let the roots hold what the government would not fund retaining walls to keep.',
      '**Terraces, trees, and seed sovereignty**\nGrace and twelve neighbours dug contour bunds by hand during the dry season. They grafted avocado onto hardy rootstock along the upper ridge and kept a seed jar of a local bean variety that tolerates short wet windows. "Commercial seed companies want us to buy every year," she says. "Our grandparents did not farm that way."',
      'Within two seasons, erosion visible from the road had slowed. By the fourth, Grace was selling surplus avocados at the Kabale market and teaching the technique at a farmers\' field school.',
      'The food forest is not pristine wilderness — it is labour-intensive, knowledge-heavy agriculture. Grace rises at five to prune, mulch, and check drip lines fed by a small rainwater tank. Her teenage daughter keeps records on a smartphone, tracking which varieties performed when the March rains arrived three weeks late.',
      'Researchers from Makerere University measured organic matter in her topsoil rising from 1.8% to 4.2% over five years — a quiet carbon story with a full pantry attached.',
      'Uganda\'s national adaptation plan mentions agroforestry in passing. Grace has not read it. She has, however, hosted three busloads of visiting farmers and one deputy minister who promised — and has not yet delivered — a rural credit line for terrace tools.',
      'What works on Grace\'s hillside will not transplant unchanged to every ecology. But the principle holds: restore structure to the land before demanding yield from it. The dying hillside is now the most productive plot on her ridge — and the neighbours who mocked her for planting trees among crops are asking for cuttings.',
    ],
  },
  {
    slug: 'youth-climate-strikers-nairobi',
    title: 'Youth Climate Strikers in Nairobi Are Demanding More Than Promises',
    category: 'Youth Voices',
    authorSlug: 'kwame-asante',
    location: 'Nairobi, Kenya',
    featured: false,
    monthsAgo: 1,
    imageIndex: 9,
    excerpt:
      'Hundreds marched from Uhuru Park to Parliament Road demanding climate finance, fossil fuel divestment, and seats at tables where Africa\'s future is negotiated without them.',
    paragraphs: [
      'The march assembled before dawn at Uhuru Park, umbrellas painted with slogans that do not translate cleanly into donor language: "Pay your debt." "No coal in Lamu." "We are the IPCC footnote — make us the headline."',
      'Organisers from Nairobi\'s Youth Climate Assembly handed out laminated cards listing three demands: honour loss-and-damage pledges, halt new fossil fuel licensing on the continent, and fund community adaptation through grants — not loans that mortgage the next generation.',
      '**Voices from the front of the march**\nAmina Kariuki, 19, carried a photograph of her grandmother\'s farm in Machakos, cracked earth where maize once stood. "They tell us to plant trees," she said. "We plant trees. Then the water truck does not come. Then they photograph us planting more trees."',
      'Behind her, a brass band from a Korogocho school played as if volume alone could move policy. It cannot — but it fills the gap between press releases and lived heat.',
      'This generation of African activists differs from its predecessors in one sharp way: they read the NDCs. They know which ministries signed which pledges. They quote IPCC summaries on megaphones outside buildings guarded by police who earn less than a COP delegate\'s per diem.',
      'Parliament Road was blocked by noon. An opposition MP emerged to accept a petition — a ritual Nairobi strikers have performed since 2019 with diminishing faith in the performance.',
      'Kwame spoke with three organisers about what comes after the march. The answer was consistent: litigation, local solar cooperatives, and storytelling that bypasses national broadcasters. "We are done asking for permission to exist on a habitable planet," said organiser Brian Otieno.',
      'The strikers dispersed before rain — the cruel irony of a climate march cut short by unpredictable weather. They will regroup next month. The promises they reject, however, remain on file in air-conditioned rooms where the temperature is always twenty-two degrees.',
    ],
  },
  {
    slug: 'solar-microgrids-rural-nigeria',
    title: 'Solar Microgrids Are Rewriting the Rules of Energy Access in Rural Nigeria',
    category: 'Energy',
    authorSlug: 'michael-eze',
    location: 'Plateau State, Nigeria',
    featured: false,
    monthsAgo: 2,
    imageIndex: 1,
    excerpt:
      'In a Plateau State village that had never seen grid power, a cooperative-funded solar microgrid now runs a clinic fridge, a school computer lab, and streetlights that keep women\'s market stalls open after dusk.',
    paragraphs: [
      'Dengi did not appear on Nigeria\'s electrification maps until a survey team arrived in 2021. Eighty kilometres from Jos, the village of 1,400 people had relied on kerosene lamps and a diesel generator that ran two hours on market days — when fuel was affordable.',
      'A Lagos-based social enterprise partnered with a local cooperative to install a 32-kilowatt solar microgrid: panels on the clinic roof, battery storage in a secured shed, and prepaid meters in sixty households. Total capital cost: roughly $38,000, half from a climate grant, half from member shares.',
      '**What changes when the lights stay on**\nNurse Esther John now refrigerates vaccines without sending a motorcycle to Jos every forty-eight hours. The secondary school\'s computer lab — three refurbished laptops — stays open until eight. Market women report evening sales up by a third since streetlights went live.',
      'Children study after chores. A woman\'s cooperative runs a phone-charging stall that pays the monthly tariff for three families who could not afford the upfront connection fee.',
      'The model is not charity. Households buy kilowatt-hours through mobile money. Two cooperative members trained as technicians earn stipends for maintenance. When a inverter failed in the second rainy season, the village fixed it in four days without waiting for Abuja.',
      'Scaling is the harder problem. Nigeria has ninety million people without reliable electricity. Dengi\'s grid serves sixty homes. Replication requires patient capital, local governance, and regulators willing to let communities own assets the national utility has failed to reach for decades.',
      'Michael Eze spent a week in Dengi interviewing technicians, ministers-by-phone, and teenagers doing homework under LED light for the first time. "The grid is political," one technician said. "Our wires are not. They either carry current or they don\'t."',
      'For Dengi, they carry current. The national grid may arrive someday. The village is no longer waiting in darkness to find out.',
    ],
  },
  {
    slug: 'africa-forests-carbon-sinks',
    title: "Africa's Forests Are Carbon Sinks the World Relies On — and Rarely Pays For",
    category: 'Biodiversity',
    authorSlug: 'zoe-ndlovu',
    location: 'Congo Basin',
    featured: false,
    monthsAgo: 2,
    imageIndex: 8,
    excerpt:
      'The Congo Basin stores more carbon per hectare than almost any ecosystem on Earth. The communities protecting it receive a fraction of the finance flowing to better-marketed rainforests elsewhere.',
    paragraphs: [
      'From a Cessna above the Congo Basin, the canopy looks endless — a corrugated green ocean breathing carbon out of the industrial north\'s exhaust. On the ground near Salonga, ranger Paul Mbelo walks a patrol line with a rifle he hopes never to fire and boots that have outlasted three funding cycles.',
      'The Congo Basin spans six countries and holds roughly six per cent of the world\'s forests. Scientists estimate it sequesters 1.2 billion tonnes of CO₂ annually — more than the Amazon in some years, with a fraction of the international attention.',
      '**The finance gap**\nAt COP meetings, "nature-based solutions" slide across screens. Pledged billions become committed millions become dispersed thousands by the time they reach a ranger\'s salary or a community forest patrol. Paul earns less per month than a single carbon offset credit generated on paper in Geneva.',
      'Indigenous and local communities legally steward large portions of the basin, yet tenure remains contested. Logging concessions overlap with protected areas on maps drawn in capitals far from the rivers that actually define boundaries.',
      'Zoe interviewed carbon market researchers who argue the current architecture rewards measurement over stewardship — paying for verified tonnes while underfunding the people who prevent tonnes from being released in the first place.',
      'There are exceptions. A community concession in the Democratic Republic of Congo has channelled modest REDD+ revenue into schools and midwife kits. A Gabonese national park partnership employs former poachers as guides. These are patches, not a system.',
      '> "The world wants our forest in its spreadsheet. It does not want our children in its universities." — Community negotiator, Mbandaka',
      'The injustice is not abstract. Every tonne the basin absorbs is a tonne the developed world does not have to cut at home. Every year finance falls short, the incentive to convert forest to farmland or mine edge increases.',
      'Paul Mbelo will patrol tomorrow regardless. The question for negotiators is whether they will finally pay for the service he provides — or continue treating Africa\'s lungs as a public good with a private cost borne by the poorest.',
    ],
  },
  {
    slug: 'rains-stopped-climate-grief-horn-africa',
    title: 'When the Rains Stopped Coming: Climate Grief in the Horn of Africa',
    category: 'Climate Change',
    authorSlug: 'fatima-al-rashid',
    location: 'Horn of Africa',
    featured: false,
    monthsAgo: 3,
    imageIndex: 2,
    excerpt:
      'Three failed rainy seasons did not only kill livestock in Somalia and Ethiopia — they unravelled identities built on knowing when the rains would come, and where home would be when they did.',
    paragraphs: [
      'Pastoralist cultures in the Horn of Africa measure time in migrations, not calendars. When the gu rains fail, herds move. When they fail again, families split — some to camps, some to towns, some across borders that maps treat as fixed and bodies experience as suggestions.',
      'Fatima spent six weeks in displacement corridors between Somalia and Ethiopia, not to count heads — aid agencies do that — but to listen to what people say when the microphones are off.',
      '**The vocabulary of loss**\nAbdi, 52, from the Bay region, described watching eighty goats die in a single week. "That was my pension," he said. "That was my daughter\'s school fees. Now I am a man who sits in a tent and accepts flour."',
      'Psychologists working with Médecins Sans Frontières report rising sleeplessness, aggression, and dissociation among men who led households for decades and now queue for rations. Cultural stigma around mental health means most will never see a clinician. Grief expresses itself in silence and sudden rage.',
      'Women describe a different calculus: walking farther for water, skipping meals so children eat, negotiating new forms of labour in towns where pastoral skills do not translate to wages.',
      'Climate grief here is not metaphor. It is the mourning of a way of life whose seasonal clock has broken. Elders who read clouds with generational accuracy now face skies that mock that knowledge.',
      'Humanitarian response focuses on calories and shelter — necessary, insufficient. Without spaces to narrate loss, communities carry it into the next camp, the next city, the next conflict over grazing routes compressed by drought.',
      'There are small interventions that help: radio programmes in Somali featuring elders discussing change without shame; women\'s circles that pair practical skills training with storytelling; schools that let displaced children keep livestock drawings in notebooks even when livestock are gone.',
      'The rains may return. The grief of their absence will not leave when they do. Reporting climate in the Horn means reporting psychology — the interior weather that outlasts the drought.',
    ],
  },
  {
    slug: 'ghana-illegal-gold-mines-poisoning-water',
    title: "Ghana's Illegal Gold Mines Are Poisoning the Water That Communities Depend On",
    category: 'Pollution',
    authorSlug: 'amara-diallo',
    location: 'Western Ghana',
    featured: false,
    monthsAgo: 3,
    imageIndex: 6,
    excerpt:
      'Galamsey operations are turning cocoa farmland and river systems toxic with mercury — while exports of gold continue to climb and enforcement remains sporadic.',
    paragraphs: [
      'The Pra River used to run brown after rains — sediment, not poison. Today it carries mercury downstream from thousands of unlicensed pits where young men sift ore with techniques banned in licensed mines but ubiquitous in galamsey camps.',
      'Amara followed the river from a cocoa village in Ashanti to a processing site hidden behind oil palm. The smell of diesel and chemicals hits before the sound of generators. Pits operate in shifts; when raids come, equipment moves overnight.',
      '**Who profits, who drinks the water**\nLicensed mining companies export gold through formal channels. Galamsey feeds parallel supply chains with lower traceability and higher local cost. Chiefs, politicians, and foreign buyers sit at different points on the chain; communities at the bottom drink from wells tested positive for mercury at levels neurologists call dangerous for children.',
      'Schoolteacher Abena Mensah in a downstream town showed attendance records: more children reporting headaches, more absences during hospital runs. "We teach them the water cycle," she said. "They ask why the cycle includes poison."',
      'Government task forces destroy equipment in televised operations. Within weeks, pits reopen. Farmers sell land for pit fees when cocoa prices collapse — a short-term gain that permanently sterilises soil.',
      'Environmental activists pushing for watershed protection face intimidation. Journalists photographing pits from public roads report confiscated cameras. The story is dangerous because the money is large and the victims are politically dispersed.',
      'Technical solutions exist: mercury-free processing kits, satellite monitoring, community water filtration. Political will does not — or arrives only before elections, then evaporates like the mercury it fails to control.',
      'Ghana\'s gold funds national accounts and global jewellery displays. The Pra River carries the invoice in a currency measured in damaged brains and lost futures. Until enforcement matches rhetoric, galamsey is not a side story — it is the main hydrological fact of Western Ghana.',
    ],
  },
  {
    slug: 'african-union-climate-adaptation-plan',
    title: "The African Union's Climate Adaptation Plan Sounds Ambitious — Ask the Communities It Ignores",
    category: 'Policy',
    authorSlug: 'nadia-hassan',
    location: 'Addis Ababa / East Africa',
    featured: false,
    monthsAgo: 4,
    imageIndex: 9,
    excerpt:
      'The AU\'s flagship adaptation framework promises continent-wide resilience. On the ground in Ethiopia and Kenya, funded projects are rare, delayed, and rarely designed with the communities they claim to serve.',
    paragraphs: [
      'The African Union\'s Climate Change and Resilient Development Strategy reads like a continent finally speaking with one voice: integrated water management, climate-smart agriculture, early warning systems, gender-responsive finance. The document is 112 pages. Implementation is another country.',
      'Nadia Hassan compared AU commitments with national budget lines and donor disbursement records in four member states. The gap between pledged adaptation finance and projects breaking ground exceeds 60% in every case studied.',
      '**Paper resilience**\nIn a district outside Hawassa, Ethiopia, a community adaptation plan sits laminated in the woreda office — produced with consultant support, funded by a multilateral grant, never referenced when the last drought killed millet across three kebeles. "We were consulted for one afternoon," a farmer said. "They photographed us. The plan does not know our river\'s name."',
      'Kenya\'s National Climate Change Action Plan fares better on paper and only marginally better in practice. Solar pumps promised in arid counties arrived eighteen months late, missing a planting season. Weather stations installed without training local technicians to maintain them.',
      'The AU is not powerless — it coordinates, advocates, and channels pooled finance. But member states implement, and implementation is where ambition dissolves into procurement delays, currency risk, and ministries that treat adaptation as a donor relations exercise rather than infrastructure.',
      'Sharp analysis does not require cynicism. Nadia interviewed AU technical staff who acknowledge the critique and point to nascent continental early-warning networks and a push to standardise NDC tracking. Progress exists. It is slow relative to warming.',
      'Communities ignored in planning do not wait. They dig wells, share seed, migrate, litigate. The policy question is whether continental frameworks will finally fund that ingenuity — or continue photographing it for annexes.',
      'Until finance matches rhetoric, the AU\'s adaptation plan will remain what sceptics call it: the most expensive PDF on the continent — ambitious on every page except the one where money leaves the account.',
    ],
  },
  {
    slug: 'mangroves-coming-back-senegal-coast',
    title: 'Mangroves Are Coming Back to the Senegal Coast — One Seedling at a Time',
    category: 'Solutions',
    authorSlug: 'james-mwangi',
    location: 'Casamance, Senegal',
    featured: false,
    monthsAgo: 4,
    imageIndex: 7,
    excerpt:
      'Women-led cooperatives in Casamance have replanted 800 hectares of mangrove since 2019 — restoring fisheries, buffering storms, and creating paid nursery work in villages that lost young men to migration.',
    paragraphs: [
      'At low tide in the Casamance delta, the mud smells of possibility. Women in wide-brimmed hats plant propagules in rows measured by stick and song — a rhythm learned from mothers who remember when mangroves covered channels now open to erosion.',
      'Mangroves are climate infrastructure disguised as swamp. Their roots sequester carbon at rates that rival tropical forests; their canopies shelter juvenile fish that support coastal diets; their buffers cut storm surge before it reaches rice paddies.',
      '**Cooperatives leading restoration**\nThe Kafountine Women\'s Mangrove Collective pools nursery labour, sells carbon credits through a verified community project, and negotiates with fishers to avoid cutting young trees for smoking racks. Since 2019 they have planted 800 hectares — modest on a map, transformative at village scale.',
      'Member Fatou Sarr showed James accounting books: nursery wages, school fees paid from credit sales, a motorcycle bought collectively for seed transport. "Men went to Europe," she said. "We went to the mud. The mud paid."',
      'Science partners from a Dakar university monitor survival rates and salinity. Early data show 72% establishment — high for restoration projects globally. Failures come from illegal cutting and occasional drought stress on young plants.',
      'Government agencies initially dismissed the cooperatives as NGO hobbies. After cyclone damage in neighbouring countries made national news, officials arrived for photos. Funding followed — unevenly, but enough to expand nurseries.',
      'Replication requires tenure security: communities must know they will benefit from trees they plant. Carbon markets help when contracts are transparent. Without that, restoration becomes free labour for distant offsets.',
      'The Senegal coast will not return to its twentieth-century mangrove extent in one generation. But the direction has reversed — from loss to gain, one seedling at a time, led by women who measure progress in finger-width roots and fuller nets.',
    ],
  },
  {
    slug: 'great-rift-valley-warming-faster',
    title: "East Africa's Great Rift Valley Is Warming Faster Than the Global Average",
    category: 'Climate Change',
    authorSlug: 'nadia-hassan',
    location: 'East African Rift',
    featured: false,
    monthsAgo: 5,
    imageIndex: 4,
    excerpt:
      'New station data show the Rift warming at 0.3°C per decade — nearly double the global mean — with cascading effects on glaciers, lakes, and the fifty million people who depend on their water.',
    paragraphs: [
      'Climb Kilimanjaro today and you will cross ecological zones in hours that once took days. Guides point to the recession of Furtwängler Glacier in terms both geological and personal: "When I started, ice reached that rock. My son will guide on bare scree."',
      'A consortium of East African universities published temperature records from forty-two stations along the Rift corridor. The trend: warming of roughly 0.3°C per decade since 1980, nearly double the global average, with hot extremes increasing faster than means.',
      '**Glaciers, lakes, and fifty million dependents**\nMount Kenya\'s Lewis Glacier has lost over 90% of its volume since 1930. Meltwater feeds rivers that supply Nairobi, irrigate tea estates, and generate hydropower downstream. Loss is not linear — but the direction is clear.',
      'Lake Naivasha and Lake Turkana face different pressures: abstraction for floriculture and hydropower, combined with evaporation under hotter air. Fisherfolk on Turkana report species shifts as temperatures stratify water columns.',
      'Pastoralists already adapted to variability now face novelty — rains that fail in patterns oral history does not recognise. National meteorological services issue forecasts; trust erodes when village experience and model output diverge three seasons in a row.',
      'Adaptation in the Rift cannot mean copying temperate solutions. It means shade-grown coffee trials, drought-tolerant rootstocks, early-warning systems in languages herders actually hear, and hard conversations about tourism revenue versus water security on glaciated peaks.',
      'Nadia interviewed a glaciologist who refused metaphor. "Ice does not negotiate," she said. "Politics does. We are losing the ice while politics negotiates adjectives."',
      'The Rift Valley gave humanity its origin story in fossil beds. It may now write the continent\'s climate future in exposed rock and empty cirques — unless finance and policy treat accelerated warming here as the emergency the data say it is.',
    ],
  },
  {
    slug: 'zambia-teen-wind-turbine-scrap-metal',
    title: "A 17-Year-Old in Zambia Built a Wind Turbine From Scrap Metal. Here's What She Did Next.",
    category: 'Youth Voices',
    authorSlug: 'kwame-asante',
    location: 'Choma, Zambia',
    featured: false,
    monthsAgo: 5,
    imageIndex: 6,
    excerpt:
      'Chisenga Mwamba welded a functioning turbine from scrap, powered her family\'s home, and sparked a village conversation about who gets to be an inventor when the grid stops fifty kilometres away.',
    paragraphs: [
      'Chisenga Mwamba, 17, learned welding from a uncle who fixes farm gates and learned physics from a teacher who lent her a cracked smartphone to watch engineering videos after school. The turbine in her yard is ugly and brilliant — blades cut from galvanised sheet, magnets salvaged from broken speakers, a car alternator rewired to charge a battery bank.',
      'It produces enough to light three rooms, charge phones, and run a small refrigerator her mother uses for market vegetables. The national grid ends fifty kilometres down a road that floods every rainy season.',
      '**Obstacles beyond engineering**\nWhen local officials visited after a radio story aired, they praised innovation — then noted her structure did not meet building codes written for projects with architects. A NGO offered a scholarship; paperwork sat in a district office for months.',
      'Boys in the village initially mocked the noise. Then they asked how to build their own. Chisenga started a Sunday club teaching basic circuits and safety — girls outnumber boys two to one.',
      'Energy poverty in rural Zambia is not a technology problem alone. Capital, permits, and patriarchal assumptions about who handles tools matter as much as wind speed.',
      'Kwame asked what she wants the world to know. "That we are not waiting," she said. "That scrap is not waste if you know what you need. That the grid might never come. We will still have light."',
      'Researchers caution against romanticising individual invention as policy substitute. Chisenga agrees. "I want the grid too," she laughs. "But I am not studying in the dark while ministers talk."',
      'Her next project: a shared battery bank for three households, funded by vegetable sales and a micro-grant she is too young to sign for — so her mother holds the account, and the irony is not lost on anyone.',
    ],
  },
  {
    slug: 'fishermen-lake-victoria-climate-change-real-time',
    title: 'The Fishermen of Lake Victoria Are Watching Climate Change Happen in Real Time',
    category: 'Water',
    authorSlug: 'zoe-ndlovu',
    location: 'Lake Victoria',
    featured: false,
    monthsAgo: 6,
    imageIndex: 3,
    excerpt:
      'Warming water, invasive species, and algal blooms are reshaping Africa\'s largest lake — and the daily routines of fisherfolk in Uganda and Kenya who have no other trade to fall back on.',
    paragraphs: [
      'Before dawn at Kasensero landing site, boats push into water the colour of weak tea. Fishermen who learned species by fin now consult phones for wind and haze — new rituals on an old lake.',
      'Lake Victoria\'s surface temperature has risen roughly 1°C since the 1950s — modest on paper, consequential in a shallow tropical lake where small shifts reorder ecosystems. Nile perch, introduced decades ago, now compete with warming-stressed native cichlids. Water hyacinth chokes inlets after nutrient runoff meets hotter, stratified water.',
      '**Nets that tell the story**\nJoseph Okello, third-generation fisher, spread a net that caught more algae than fish on three of the last five outings. "My grandfather\'s lake is not mine," he said. "The fish went deeper or died or ate something new. The market wants perch. The lake gives salad."',
      'Kenyan crews on the eastern shore report similar patterns — longer voyages for smaller catches, fuel costs eating margins, loans taken against boats that may not pay back if trends hold.',
      'Scientists at the Lake Victoria Fisheries Organisation track biomass and issue quotas. Enforcement is patchy; illegal gear proliferates when legal catch falls. Climate stress and overfishing braid into one knot.',
      'Adaptation is uneven. Some cooperatives trial deep-set lines and chilled storage powered by solar. Others pivot to aquaculture ponds — capital-intensive, risky. Many young men leave for city construction work; elders stay because the lake is identity, not just income.',
      'Zoe photographed landing sites at golden hour — beautiful, misleading. Beauty does not pay school fees. The photographs run beside text because readers far from the lake need to see what "warming" looks like on a face, not only a graph.',
      'Lake Victoria will not disappear like Lake Chad. Its crisis is subtler: a living system changing faster than culture and economy can absorb. The fisherfolk see it in real time — in empty nets, strange blooms, and sons who do not want the boat. The rest of the world sees it when fish prices rise at dinner. The lake connects both tables.',
    ],
  },
  {
    slug: 'seed-qa-opinion-climate-finance-debt-trap',
    title: 'Opinion: Climate Finance Is Still a Debt Trap — and Africa Knows It',
    category: 'Opinion',
    authorSlug: 'nadia-hassan',
    location: 'Nairobi, Kenya',
    featured: false,
    monthsAgo: 2,
    imageIndex: 5,
    excerpt:
      'Loans labelled "climate adaptation" are arriving with the same conditionalities as structural adjustment. Until grants outpace debt, the finance conversation is theatre.',
    paragraphs: [
      'Every climate summit produces a headline figure for Africa. Every fiscal year, finance ministries discover how little of it arrives as grants — and how much arrives as debt with green labels and familiar strings attached.',
      '**The vocabulary shift**\n"Resilience bonds," "blended finance," and "de-risking private capital" sound modern. For borrowers, they often mean the same old trade-offs: currency risk, sovereign guarantees, and projects designed for investor returns before community needs.',
      'Kenya\'s adaptation plan is not short on technical ambition. It is short on fiscal space. When a drought year empties reserves, servicing a climate-labelled loan competes with school salaries and clinic stocks. Ministers choose between default and protest.',
      '> "We are told to borrow to survive the drought. Then we repay the loan during the next drought." — County finance officer, eastern Kenya',
      'Multilateral institutions counter that concessional rates and long tenors make these instruments affordable. Tell that to a pastoral county where livestock mortality wiped out two seasons of revenue. The spreadsheet and the savanna use different calendars.',
      '**What would honest finance look like?**\nGrants tied to measurable community outcomes, not export credit. Loss-and-damage funds disbursed without eighteen-month accreditation queues. Transparent contracts published in languages farmers actually read.',
      'Private capital has a role — but not as default setting. Public goods like groundwater monitoring and early-warning systems should not depend on equity returns.',
      'Until grant share crosses a threshold ministers can defend at home, "climate finance" will remain a debt trap with better branding. Africa knows it. The question is whether the next COP will admit it.',
    ],
  },
  {
    slug: 'seed-qa-cape-town-day-zero-lessons',
    title: 'Cape Town Dodged Day Zero — But the Water Crisis Never Left',
    category: 'Water',
    authorSlug: 'zoe-ndlovu',
    location: 'Cape Town, South Africa',
    featured: false,
    monthsAgo: 4,
    imageIndex: 9,
    excerpt:
      'The city that made global headlines for nearly running dry still lives with rationing psychology, unequal access, and infrastructure debt — a preview for other African metros.',
    paragraphs: [
      'In 2018, Cape Town\'s taps nearly ran dry. Day Zero became a global shorthand for urban water collapse. The date was postponed. The structural pressures were not.',
      'Wealthy suburbs installed tanks and boreholes. Informal settlements never had reliable supply to begin with. The crisis mapped inequality onto hydrology with uncomfortable clarity.',
      '**Infrastructure lag**\nDam levels recovered after exceptional rains, but leakage from ageing pipes still wastes a staggering share of treated water. Maintenance budgets compete with political vanity projects.',
      'Farmers in the Boland wrestle with allocation formulas that privilege export crops. Smallholders downstream ask why vineyards drink while their spinach wilts.',
      'Behaviour change campaigns worked — briefly. Shower timers and social shaming cut consumption. Without permanent pricing signals and repair crews, old habits return when headlines fade.',
      'Scientists model hotter, drier summers for the Western Cape. Adaptation means recycling wastewater at scale, restoring catchment vegetation, and planning for migrants from rural districts where wells failed first.',
      'Cape Town dodged the catastrophe on the calendar. It did not dodge the lesson: water security is governance, not luck.',
    ],
  },
  {
    slug: 'seed-qa-morocco-noor-solar-who-owns-the-sun',
    title: 'Morocco Built the World\'s Largest Solar Complex — Who Owns the Sun?',
    category: 'Energy',
    authorSlug: 'michael-eze',
    location: 'Ouarzazate, Morocco',
    featured: true,
    monthsAgo: 1,
    imageIndex: 4,
    excerpt:
      'The Noor complex is a engineering marvel and a geopolitical statement. For villages in its shadow, the benefits are brighter — but not evenly distributed.',
    paragraphs: [
      'From the highway, the Noor Ouarzazate complex shimmers like a lake in the desert — curved mirrors tracking a sun that feels personal at this latitude. Morocco marketed it as proof that Africa can lead on clean power.',
      'The engineering is real: concentrated solar and photovoltaic phases feeding the national grid, storage experiments, technicians trained on site. Diplomats tour the control room and photograph mirrors at golden hour.',
      '**Follow the electrons**\nElectricity does not automatically mean local jobs or cheaper bills. Transmission losses and tariff structures determine who feels the benefit. Some nearby villages still report outages while export contracts hum.',
      'Concentrated solar uses water for cleaning mirrors in an arid province. Designers recirculate and source carefully, but every litre has an opportunity cost in a basin shared with farmers and oasis towns.',
      'Financing blends public, multilateral, and private capital — each with reporting requirements and timelines that do not always match community planning cycles.',
      'Morocco\'s renewable ambition is genuine. So is the question African energy reporters must keep asking: who owns the sun on paper, who pays when the sun does not shine, and who gets left in the shadow of the marketing brochure?',
      'Noor is not a cautionary tale against ambition. It is a reminder that megawatts are only the beginning of an energy story.',
    ],
  },
]
