/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    contributors: ContributorAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    stories: Story;
    contributors: Contributor;
    solutions: Solution;
    organizations: Organization;
    'impact-updates': ImpactUpdate;
    'interest-leads': InterestLead;
    programmes: Programme;
    series: Series;
    'podcast-episodes': PodcastEpisode;
    videos: Video;
    'partner-organisations': PartnerOrganisation;
    'community-projects': CommunityProject;
    'contact-submissions': ContactSubmission;
    'newsletter-subscribers': NewsletterSubscriber;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    contributors: ContributorsSelect<false> | ContributorsSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    'impact-updates': ImpactUpdatesSelect<false> | ImpactUpdatesSelect<true>;
    'interest-leads': InterestLeadsSelect<false> | InterestLeadsSelect<true>;
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    series: SeriesSelect<false> | SeriesSelect<true>;
    'podcast-episodes': PodcastEpisodesSelect<false> | PodcastEpisodesSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    'partner-organisations': PartnerOrganisationsSelect<false> | PartnerOrganisationsSelect<true>;
    'community-projects': CommunityProjectsSelect<false> | CommunityProjectsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Contributor;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ContributorAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Editorial queue: filter by status "In Review" for submitted contributor stories.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  category?: (number | null) | Category;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | Contributor;
  status?: ('draft' | 'in-review' | 'published') | null;
  featured?: boolean | null;
  readingTime?: number | null;
  publishedAt?: string | null;
  location?: string | null;
  searchText?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  ogImage?: (number | null) | Media;
  relatedStories?: (number | Story)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Approved contributors can log into /dashboard. Set applicationStatus to Approved and assign a password.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contributors".
 */
export interface Contributor {
  id: number;
  name: string;
  slug?: string | null;
  role?: string | null;
  region?: string | null;
  bio?: string | null;
  profilePhoto?: (number | null) | Media;
  expertise?:
    | {
        area?: string | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  applicationStatus?: ('pending' | 'approved' | 'rejected') | null;
  portfolioUrl?: string | null;
  /**
   * Structured contributor application payload (from the public apply form).
   */
  applicationDetails?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'contributors';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  title: string;
  slug: string;
  organization?: (number | null) | Organization;
  thesis?: string | null;
  category?: (number | null) | Category;
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  location?: string | null;
  country?: string | null;
  /**
   * Mark as Global when the solution is proven outside Africa and ready to replicate on the continent.
   */
  replicationScope?: ('africa' | 'global') | null;
  locationName?: string | null;
  statHighlight?: string | null;
  keyImpact?:
    | {
        label: string;
        value: string;
        unit?: string | null;
        id?: string | null;
      }[]
    | null;
  sectors?: ('agriculture' | 'energy' | 'water' | 'biodiversity' | 'pollution' | 'climate-justice')[] | null;
  solutionStatus?: ('piloted' | 'scaling' | 'established') | null;
  verificationTier?: ('self_reported' | 'field_reported' | 'independently_verified') | null;
  verifiedBy?: ('field-reporter' | 'community-validated' | 'partner-confirmed') | null;
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  partnerOrgs?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  fundingStatus?: ('seeking' | 'partial' | 'funded' | 'not_seeking') | null;
  fundingNeed?: {
    amount?: string | null;
    currency?: string | null;
    timeline?: string | null;
    useOfFunds?: string | null;
  };
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedStories?: (number | Story)[] | null;
  sdgTags?: ('sdg-1' | 'sdg-2' | 'sdg-6' | 'sdg-7' | 'sdg-13' | 'sdg-15')[] | null;
  onePagerUrl?: string | null;
  publishedAt?: string | null;
  heroImage?: (number | null) | Media;
  verified?: boolean | null;
  featured?: boolean | null;
  published?: boolean | null;
  relatedStory?: (number | null) | Story;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  slug: string;
  type?: ('ngo' | 'cooperative' | 'social-enterprise' | 'research' | 'community' | 'government') | null;
  tagline?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  logo?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  website?: string | null;
  donationUrl?: string | null;
  foundedYear?: number | null;
  hqLocation?: string | null;
  regions?:
    | (
        | 'east-africa'
        | 'west-africa'
        | 'southern-africa'
        | 'sahel'
        | 'horn-of-africa'
        | 'central-africa'
        | 'pan-african'
      )[]
    | null;
  focusAreas?: ('agriculture' | 'energy' | 'water' | 'biodiversity' | 'pollution' | 'climate-justice')[] | null;
  team?:
    | {
        name: string;
        role?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  socials?: {
    twitter?: string | null;
    linkedin?: string | null;
    instagram?: string | null;
  };
  verified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-updates".
 */
export interface ImpactUpdate {
  id: number;
  project: number | Solution;
  date: string;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  metrics?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  media?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interest-leads".
 */
export interface InterestLead {
  id: number;
  project?: (number | null) | Solution;
  organization?: (number | null) | Organization;
  type: 'support' | 'partner' | 'intro' | 'download';
  name: string;
  email: string;
  organizationName?: string | null;
  message?: string | null;
  consent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes".
 */
export interface Programme {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  cadence?: string | null;
  accentColor?: string | null;
  applicationOpenDate?: string | null;
  applicationCloseDate?: string | null;
  applicationInstructions?: string | null;
  /**
   * Optional. Paste the host organisation’s application form URL. Leave blank to use the EcoDiaries application form.
   */
  applicationUrl?: string | null;
  featured?: boolean | null;
  opportunityType: 'programme' | 'grant' | 'fellowship' | 'event';
  status?: ('open' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series".
 */
export interface Series {
  id: number;
  name: string;
  /**
   * URL slug for /watch/series/[slug]
   */
  slug?: string | null;
  description?: string | null;
  coverArt?: (number | null) | Media;
  type?: ('podcast' | 'video') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcast-episodes".
 */
export interface PodcastEpisode {
  id: number;
  title: string;
  slug: string;
  series?: (number | null) | Series;
  episodeNumber?: number | null;
  seasonNumber?: number | null;
  audioFile?: (number | null) | Media;
  embedUrl?: string | null;
  /**
   * Display label e.g. 24 min
   */
  duration?: string | null;
  /**
   * Length in seconds for the player
   */
  durationSeconds?: number | null;
  description?: string | null;
  thumbnail?: (number | null) | Media;
  coverArt?: (number | null) | Media;
  publishedAt?: string | null;
  featured?: boolean | null;
  hosts?:
    | {
        isExternal?: boolean | null;
        contributor?: (number | null) | Contributor;
        role?: ('Host' | 'Co-host' | 'Guest' | 'Producer' | 'Reporter') | null;
        externalName?: string | null;
        externalBio?: string | null;
        externalAvatar?: (number | null) | Media;
        externalSocialUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  slug: string;
  videoFile?: (number | null) | Media;
  embedUrl?: string | null;
  thumbnail?: (number | null) | Media;
  categoryTag?: ('Documentary' | 'Field Report' | 'Interview' | 'Community Spotlight' | 'Educational' | 'Short') | null;
  /**
   * Display label e.g. 18:45
   */
  duration?: string | null;
  /**
   * Length in seconds for the player
   */
  durationSeconds?: number | null;
  description?: string | null;
  series?: (number | null) | Series;
  publishedAt?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-organisations".
 */
export interface PartnerOrganisation {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  link?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-projects".
 */
export interface CommunityProject {
  id: number;
  title: string;
  description?: string | null;
  image?: (number | null) | Media;
  relatedStory?: (number | null) | Story;
  updatedAt: string;
  createdAt: string;
}
/**
 * Submissions from the public contact form. Mark as read or responded — do not create manually.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  reason: 'story-tip' | 'contributor' | 'partnership' | 'programmes' | 'other';
  message: string;
  status?: ('new' | 'read' | 'responded') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  status?: ('pending' | 'confirmed' | 'unsubscribed') | null;
  confirmToken?: string | null;
  confirmedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'contributors';
        value: number | Contributor;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'impact-updates';
        value: number | ImpactUpdate;
      } | null)
    | ({
        relationTo: 'interest-leads';
        value: number | InterestLead;
      } | null)
    | ({
        relationTo: 'programmes';
        value: number | Programme;
      } | null)
    | ({
        relationTo: 'series';
        value: number | Series;
      } | null)
    | ({
        relationTo: 'podcast-episodes';
        value: number | PodcastEpisode;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'partner-organisations';
        value: number | PartnerOrganisation;
      } | null)
    | ({
        relationTo: 'community-projects';
        value: number | CommunityProject;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'contributors';
        value: number | Contributor;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'contributors';
        value: number | Contributor;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  body?: T;
  author?: T;
  status?: T;
  featured?: T;
  readingTime?: T;
  publishedAt?: T;
  location?: T;
  searchText?: T;
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  relatedStories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contributors_select".
 */
export interface ContributorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  region?: T;
  bio?: T;
  profilePhoto?: T;
  expertise?:
    | T
    | {
        area?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  applicationStatus?: T;
  portfolioUrl?: T;
  applicationDetails?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  organization?: T;
  thesis?: T;
  category?: T;
  summary?: T;
  body?: T;
  location?: T;
  country?: T;
  replicationScope?: T;
  locationName?: T;
  statHighlight?: T;
  keyImpact?:
    | T
    | {
        label?: T;
        value?: T;
        unit?: T;
        id?: T;
      };
  sectors?: T;
  solutionStatus?: T;
  verificationTier?: T;
  verifiedBy?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  partnerOrgs?:
    | T
    | {
        name?: T;
        id?: T;
      };
  fundingStatus?: T;
  fundingNeed?:
    | T
    | {
        amount?: T;
        currency?: T;
        timeline?: T;
        useOfFunds?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  relatedStories?: T;
  sdgTags?: T;
  onePagerUrl?: T;
  publishedAt?: T;
  heroImage?: T;
  verified?: T;
  featured?: T;
  published?: T;
  relatedStory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  tagline?: T;
  bio?: T;
  logo?: T;
  coverImage?: T;
  website?: T;
  donationUrl?: T;
  foundedYear?: T;
  hqLocation?: T;
  regions?: T;
  focusAreas?: T;
  team?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        twitter?: T;
        linkedin?: T;
        instagram?: T;
      };
  verified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-updates_select".
 */
export interface ImpactUpdatesSelect<T extends boolean = true> {
  project?: T;
  date?: T;
  title?: T;
  body?: T;
  metrics?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  media?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interest-leads_select".
 */
export interface InterestLeadsSelect<T extends boolean = true> {
  project?: T;
  organization?: T;
  type?: T;
  name?: T;
  email?: T;
  organizationName?: T;
  message?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  cadence?: T;
  accentColor?: T;
  applicationOpenDate?: T;
  applicationCloseDate?: T;
  applicationInstructions?: T;
  applicationUrl?: T;
  featured?: T;
  opportunityType?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series_select".
 */
export interface SeriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  coverArt?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcast-episodes_select".
 */
export interface PodcastEpisodesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  series?: T;
  episodeNumber?: T;
  seasonNumber?: T;
  audioFile?: T;
  embedUrl?: T;
  duration?: T;
  durationSeconds?: T;
  description?: T;
  thumbnail?: T;
  coverArt?: T;
  publishedAt?: T;
  featured?: T;
  hosts?:
    | T
    | {
        isExternal?: T;
        contributor?: T;
        role?: T;
        externalName?: T;
        externalBio?: T;
        externalAvatar?: T;
        externalSocialUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  videoFile?: T;
  embedUrl?: T;
  thumbnail?: T;
  categoryTag?: T;
  duration?: T;
  durationSeconds?: T;
  description?: T;
  series?: T;
  publishedAt?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-organisations_select".
 */
export interface PartnerOrganisationsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  link?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-projects_select".
 */
export interface CommunityProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  relatedStory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  reason?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  confirmToken?: T;
  confirmedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  impactStats?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  missionCopy?: string | null;
  visionCopy?: string | null;
  socialLinks?:
    | {
        platform?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  impactStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  missionCopy?: T;
  visionCopy?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}